package verses

var allVerses = []Verse{
	{
		Reference: "John 3:16",
		Text:      "For God so loved the world that He gave His only begotten Son, that whoever believes in Him should not perish but have everlasting life.",
		Book:      "John",
		Testament: "new",
	},
	{
		Reference: "Romans 5:8",
		Text:      "But God demonstrates His own love toward us, in that while we were still sinners, Christ died for us.",
		Book:      "Romans",
		Testament: "new",
	},
	{
		Reference: "Ephesians 2:8-9",
		Text:      "For by grace you have been saved through faith, and that not of yourselves; it is the gift of God, not of works, lest anyone should boast.",
		Book:      "Ephesians",
		Testament: "new",
	},
	{
		Reference: "1 Corinthians 15:3-4",
		Text:      "For I delivered to you first of all that which I also received: that Christ died for our sins according to the Scriptures, and that He was buried, and that He rose again the third day according to the Scriptures.",
		Book:      "1 Corinthians",
		Testament: "new",
	},
	{
		Reference: "Romans 10:9",
		Text:      "That if you confess with your mouth the Lord Jesus and believe in your heart that God has raised Him from the dead, you will be saved.",
		Book:      "Romans",
		Testament: "new",
	},
	{
		Reference: "Acts 4:12",
		Text:      "Nor is there salvation in any other, for there is no other name under heaven given among men by which we must be saved.",
		Book:      "Acts",
		Testament: "new",
	},
	{
		Reference: "2 Corinthians 5:21",
		Text:      "For He made Him who knew no sin to be sin for us, that we might become the righteousness of God in Him.",
		Book:      "2 Corinthians",
		Testament: "new",
	},
	{
		Reference: "Titus 3:5",
		Text:      "Not by works of righteousness which we have done, but according to His mercy He saved us, through the washing of regeneration and renewing of the Holy Spirit.",
		Book:      "Titus",
		Testament: "new",
	},
	{
		Reference: "Romans 3:23-24",
		Text:      "For all have sinned and fall short of the glory of God, being justified freely by His grace through the redemption that is in Christ Jesus.",
		Book:      "Romans",
		Testament: "new",
	},
	{
		Reference: "1 John 1:9",
		Text:      "If we confess our sins, He is faithful and just to forgive us our sins and to cleanse us from all unrighteousness.",
		Book:      "1 John",
		Testament: "new",
	},
	{
		Reference: "Psalm 103:8",
		Text:      "The LORD is merciful and gracious, slow to anger, and abounding in mercy.",
		Book:      "Psalm",
		Testament: "old",
	},
	{
		Reference: "1 John 4:8",
		Text:      "He who does not love does not know God, for God is love.",
		Book:      "1 John",
		Testament: "new",
	},
	{
		Reference: "Exodus 34:6-7",
		Text:      "The LORD, the LORD God, merciful and gracious, longsuffering, and abounding in goodness and truth, keeping mercy for thousands, forgiving iniquity and transgression and sin.",
		Book:      "Exodus",
		Testament: "old",
	},
	{
		Reference: "Psalm 46:1",
		Text:      "God is our refuge and strength, a very present help in trouble.",
		Book:      "Psalm",
		Testament: "old",
	},
	{
		Reference: "Isaiah 6:3",
		Text:      "Holy, holy, holy is the LORD of hosts; the whole earth is full of His glory!",
		Book:      "Isaiah",
		Testament: "old",
	},
	{
		Reference: "Deuteronomy 7:9",
		Text:      "Therefore know that the LORD your God, He is God, the faithful God who keeps covenant and mercy for a thousand generations with those who love Him and keep His commandments.",
		Book:      "Deuteronomy",
		Testament: "old",
	},
	{
		Reference: "Psalm 145:8-9",
		Text:      "The LORD is gracious and full of compassion, slow to anger and great in mercy. The LORD is good to all, and His tender mercies are over all His works.",
		Book:      "Psalm",
		Testament: "old",
	},
	{
		Reference: "James 1:17",
		Text:      "Every good gift and every perfect gift is from above, and comes down from the Father of lights, with whom there is no variation or shadow of turning.",
		Book:      "James",
		Testament: "new",
	},
	{
		Reference: "1 John 1:5",
		Text:      "God is light and in Him is no darkness at all.",
		Book:      "1 John",
		Testament: "new",
	},
	{
		Reference: "Psalm 139:7-8",
		Text:      "Where can I go from Your Spirit? Or where can I flee from Your presence? If I ascend into heaven, You are there; if I make my bed in hell, behold, You are there.",
		Book:      "Psalm",
		Testament: "old",
	},
	{
		Reference: "Philippians 4:13",
		Text:      "I can do all things through Christ who strengthens me.",
		Book:      "Philippians",
		Testament: "new",
	},
	{
		Reference: "Isaiah 40:31",
		Text:      "But those who wait on the LORD shall renew their strength; they shall mount up with wings like eagles, they shall run and not be weary, they shall walk and not faint.",
		Book:      "Isaiah",
		Testament: "old",
	},
	{
		Reference: "Romans 8:28",
		Text:      "And we know that all things work together for good to those who love God, to those who are the called according to His purpose.",
		Book:      "Romans",
		Testament: "new",
	},
	{
		Reference: "Psalm 23:4",
		Text:      "Yea, though I walk through the valley of the shadow of death, I will fear no evil; for You are with me; Your rod and Your staff, they comfort me.",
		Book:      "Psalm",
		Testament: "old",
	},
	{
		Reference: "2 Corinthians 12:9",
		Text:      "And He said to me, 'My grace is sufficient for you, for My strength is made perfect in weakness.' Therefore most gladly I will rather boast in my infirmities, that the power of Christ may rest upon me.",
		Book:      "2 Corinthians",
		Testament: "new",
	},
	{
		Reference: "Isaiah 41:10",
		Text:      "Fear not, for I am with you; be not dismayed, for I am your God. I will strengthen you, yes, I will help you, I will uphold you with My righteous right hand.",
		Book:      "Isaiah",
		Testament: "old",
	},
	{
		Reference: "Psalm 34:18",
		Text:      "The LORD is near to those who have a broken heart, and saves such as have a contrite spirit.",
		Book:      "Psalm",
		Testament: "old",
	},
	{
		Reference: "Matthew 11:28",
		Text:      "Come to Me, all you who labor and are heavy laden, and I will give you rest.",
		Book:      "Matthew",
		Testament: "new",
	},
	{
		Reference: "Joshua 1:9",
		Text:      "Have I not commanded you? Be strong and of good courage; do not be afraid, nor be dismayed, for the LORD your God is with you wherever you go.",
		Book:      "Joshua",
		Testament: "old",
	},
	{
		Reference: "Psalm 55:22",
		Text:      "Cast your burden on the LORD, and He shall sustain you; He shall never permit the righteous to be moved.",
		Book:      "Psalm",
		Testament: "old",
	},
	{
		Reference: "Romans 12:1-2",
		Text:      "I beseech you therefore, brethren, by the mercies of God, that you present your bodies a living sacrifice, holy, acceptable to God, which is your reasonable service. And do not be conformed to this world, but be transformed by the renewing of your mind.",
		Book:      "Romans",
		Testament: "new",
	},
	{
		Reference: "Galatians 2:20",
		Text:      "I have been crucified with Christ; it is no longer I who live, but Christ lives in me; and the life which I now live in the flesh I live by faith in the Son of God, who loved me and gave Himself for me.",
		Book:      "Galatians",
		Testament: "new",
	},
	{
		Reference: "Philippians 2:12-13",
		Text:      "Work out your own salvation with fear and trembling; for it is God who works in you both to will and to do for His good pleasure.",
		Book:      "Philippians",
		Testament: "new",
	},
	{
		Reference: "2 Peter 1:3",
		Text:      "As His divine power has given to us all things that pertain to life and godliness, through the knowledge of Him who called us by glory and virtue.",
		Book:      "2 Peter",
		Testament: "new",
	},
	{
		Reference: "1 Thessalonians 4:3",
		Text:      "For this is the will of God, your sanctification.",
		Book:      "1 Thessalonians",
		Testament: "new",
	},
	{
		Reference: "Colossians 3:2",
		Text:      "Set your mind on things above, not on things on the earth.",
		Book:      "Colossians",
		Testament: "new",
	},
	{
		Reference: "1 Peter 1:15-16",
		Text:      "But as He who called you is holy, you also be holy in all your conduct, because it is written, 'Be holy, for I am holy.'",
		Book:      "1 Peter",
		Testament: "new",
	},
	{
		Reference: "Philippians 1:6",
		Text:      "Being confident of this very thing, that He who has begun a good work in you will complete it until the day of Jesus Christ.",
		Book:      "Philippians",
		Testament: "new",
	},
	{
		Reference: "2 Corinthians 3:18",
		Text:      "But we all, with unveiled face, beholding as in a mirror the glory of the Lord, are being transformed into the same image from glory to glory, just as by the Spirit of the Lord.",
		Book:      "2 Corinthians",
		Testament: "new",
	},
	{
		Reference: "Romans 6:11",
		Text:      "Likewise you also, reckon yourselves to be dead indeed to sin, but alive to God in Christ Jesus our Lord.",
		Book:      "Romans",
		Testament: "new",
	},
	{
		Reference: "Hebrews 12:1-2",
		Text:      "Therefore we also, since we are surrounded by so great a cloud of witnesses, let us lay aside every weight, and the sin which so easily ensnares us, and let us run with endurance the race that is set before us, looking unto Jesus, the author and finisher of our faith.",
		Book:      "Hebrews",
		Testament: "new",
	},
	{
		Reference: "James 1:12",
		Text:      "Blessed is the man who endures temptation; for when he has been approved, he will receive the crown of life which the Lord has promised to those who love Him.",
		Book:      "James",
		Testament: "new",
	},
	{
		Reference: "Revelation 2:10",
		Text:      "Be faithful until death, and I will give you the crown of life.",
		Book:      "Revelation",
		Testament: "new",
	},
	{
		Reference: "1 Corinthians 15:58",
		Text:      "Therefore, my beloved brethren, be steadfast, immovable, always abounding in the work of the Lord, knowing that your labor is not in vain in the Lord.",
		Book:      "1 Corinthians",
		Testament: "new",
	},
	{
		Reference: "Galatians 6:9",
		Text:      "And let us not grow weary while doing good, for in due season we shall reap if we do not lose heart.",
		Book:      "Galatians",
		Testament: "new",
	},
	{
		Reference: "2 Timothy 4:7",
		Text:      "I have fought the good fight, I have finished the race, I have kept the faith.",
		Book:      "2 Timothy",
		Testament: "new",
	},
	{
		Reference: "Hebrews 10:23",
		Text:      "Let us hold fast the confession of our hope without wavering, for He who promised is faithful.",
		Book:      "Hebrews",
		Testament: "new",
	},
	{
		Reference: "1 Peter 5:10",
		Text:      "But may the God of all grace, who called us to His eternal glory by Christ Jesus, after you have suffered a while, perfect, establish, strengthen, and settle you.",
		Book:      "1 Peter",
		Testament: "new",
	},
	{
		Reference: "Revelation 2:9",
		Text:      "I know your works, tribulation, and poverty (but you are rich); and I know the blasphemy of those who say they are Jews and are not, but are a synagogue of Satan.",
		Book:      "Revelation",
		Testament: "new",
	},
	{
		Reference: "Revelation 3:9",
		Text:      "Indeed I will make those of the synagogue of Satan, who say they are Jews and are not, but lie—indeed I will make them come and worship before your feet, and to know that I have loved you.",
		Book:      "Revelation",
		Testament: "new",
	},
	{
		Reference: "Revelation 1:8",
		Text:      "I am the Alpha and the Omega, the Beginning and the End,' says the Lord, 'who is and who was and who is to come, the Almighty.'",
		Book:      "Revelation",
		Testament: "new",
	},
	{
		Reference: "Revelation 21:4",
		Text:      "And God will wipe away every tear from their eyes; there shall be no more death, nor sorrow, nor crying. There shall be no more pain, for the former things have passed away.",
		Book:      "Revelation",
		Testament: "new",
	},
	{
		Reference: "Revelation 22:12",
		Text:      "And behold, I am coming quickly, and My reward is with Me, to give to every one according to his work.",
		Book:      "Revelation",
		Testament: "new",
	},
	{
		Reference: "Matthew 24:35",
		Text:      "Heaven and earth will pass away, but My words will by no means pass away.",
		Book:      "Matthew",
		Testament: "new",
	},
	{
		Reference: "1 Thessalonians 4:16-17",
		Text:      "For the Lord Himself will descend from heaven with a shout, with the voice of an archangel, and with the trumpet of God. And the dead in Christ will rise first. Then we who are alive and remain shall be caught up together with them in the clouds to meet the Lord in the air.",
		Book:      "1 Thessalonians",
		Testament: "new",
	},
	{
		Reference: "Proverbs 3:5-6",
		Text:      "Trust in the LORD with all your heart, and lean not on your own understanding; in all your ways acknowledge Him, and He shall direct your paths.",
		Book:      "Proverbs",
		Testament: "old",
	},
	{
		Reference: "James 1:5",
		Text:      "If any of you lacks wisdom, let him ask of God, who gives to all liberally and without reproach, and it will be given to him.",
		Book:      "James",
		Testament: "new",
	},
	{
		Reference: "Proverbs 16:3",
		Text:      "Commit your works to the LORD, and your thoughts will be established.",
		Book:      "Proverbs",
		Testament: "old",
	},
	{
		Reference: "Proverbs 18:10",
		Text:      "The name of the LORD is a strong tower; the righteous run to it and are safe.",
		Book:      "Proverbs",
		Testament: "old",
	},
	{
		Reference: "Ecclesiastes 12:13",
		Text:      "Let us hear the conclusion of the whole matter: Fear God and keep His commandments, for this is man's all.",
		Book:      "Ecclesiastes",
		Testament: "old",
	},
	{
		Reference: "Proverbs 4:23",
		Text:      "Keep your heart with all diligence, for out of it spring the issues of life.",
		Book:      "Proverbs",
		Testament: "old",
	},
	{
		Reference: "Proverbs 27:17",
		Text:      "As iron sharpens iron, so a man sharpens the countenance of his friend.",
		Book:      "Proverbs",
		Testament: "old",
	},
	{
		Reference: "Colossians 3:23",
		Text:      "And whatever you do, do it heartily, as to the Lord and not to men.",
		Book:      "Colossians",
		Testament: "new",
	},
	{
		Reference: "Proverbs 11:25",
		Text:      "The generous soul will be made rich, and he who waters will also be watered himself.",
		Book:      "Proverbs",
		Testament: "old",
	},
	{
		Reference: "Matthew 6:33",
		Text:      "But seek first the kingdom of God and His righteousness, and all these things shall be added to you.",
		Book:      "Matthew",
		Testament: "new",
	},
	{
		Reference: "John 13:34-35",
		Text:      "A new commandment I give to you, that you love one another; as I have loved you, that you also love one another. By this all will know that you are My disciples, if you have love for one another.",
		Book:      "John",
		Testament: "new",
	},
	{
		Reference: "1 Corinthians 13:4-5",
		Text:      "Love suffers long and is kind; love does not envy; love does not parade itself, is not puffed up; does not behave rudely, does not seek its own, is not provoked, thinks no evil.",
		Book:      "1 Corinthians",
		Testament: "new",
	},
	{
		Reference: "Mark 12:30-31",
		Text:      "And you shall love the LORD your God with all your heart, with all your soul, with all your mind, and with all your strength.' This is the first commandment. And the second, like it, is this: 'You shall love your neighbor as yourself.'",
		Book:      "Mark",
		Testament: "new",
	},
	{
		Reference: "1 John 4:19",
		Text:      "We love Him because He first loved us.",
		Book:      "1 John",
		Testament: "new",
	},
	{
		Reference: "Galatians 5:13",
		Text:      "For you, brethren, have been called to liberty; only do not use liberty as an opportunity for the flesh, but through love serve one another.",
		Book:      "Galatians",
		Testament: "new",
	},
	{
		Reference: "Philippians 4:6-7",
		Text:      "Be anxious for nothing, but in everything by prayer and supplication, with thanksgiving, let your requests be made known to God; and the peace of God, which surpasses all understanding, will guard your hearts and minds through Christ Jesus.",
		Book:      "Philippians",
		Testament: "new",
	},
	{
		Reference: "1 Thessalonians 5:16-18",
		Text:      "Rejoice always, pray without ceasing, in everything give thanks; for this is the will of God in Christ Jesus for you.",
		Book:      "1 Thessalonians",
		Testament: "new",
	},
	{
		Reference: "Jeremiah 29:11",
		Text:      "For I know the thoughts that I think toward you, says the LORD, thoughts of peace and not of evil, to give you a future and a hope.",
		Book:      "Jeremiah",
		Testament: "old",
	},
	{
		Reference: "Matthew 7:7",
		Text:      "Ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you.",
		Book:      "Matthew",
		Testament: "new",
	},
	{
		Reference: "Psalm 16:11",
		Text:      "You will show me the path of life; in Your presence is fullness of joy; at Your right hand are pleasures forevermore.",
		Book:      "Psalm",
		Testament: "old",
	},
	{
		Reference: "John 15:7",
		Text:      "If you abide in Me, and My words abide in you, you will ask what you desire, and it shall be done for you.",
		Book:      "John",
		Testament: "new",
	},
	{
		Reference: "Psalm 37:4",
		Text:      "Delight yourself also in the LORD, and He shall give you the desires of your heart.",
		Book:      "Psalm",
		Testament: "old",
	},
	{
		Reference: "James 5:16",
		Text:      "The effective, fervent prayer of a righteous man avails much.",
		Book:      "James",
		Testament: "new",
	},
	{
		Reference: "John 14:27",
		Text:      "Peace I leave with you, My peace I give to you; not as the world gives do I give to you. Let not your heart be troubled, neither let it be afraid.",
		Book:      "John",
		Testament: "new",
	},
	{
		Reference: "Isaiah 26:3",
		Text:      "You will keep him in perfect peace, whose mind is stayed on You, because he trusts in You.",
		Book:      "Isaiah",
		Testament: "old",
	},
	{
		Reference: "Psalm 4:8",
		Text:      "I will both lie down in peace, and sleep; for You alone, O LORD, make me dwell in safety.",
		Book:      "Psalm",
		Testament: "old",
	},
	{
		Reference: "Proverbs 29:25",
		Text:      "The fear of man brings a snare, but whoever trusts in the LORD shall be safe.",
		Book:      "Proverbs",
		Testament: "old",
	},
	{
		Reference: "Nahum 1:7",
		Text:      "The LORD is good, a stronghold in the day of trouble; and He knows those who trust in Him.",
		Book:      "Nahum",
		Testament: "old",
	},
	{
		Reference: "Psalm 91:1-2",
		Text:      "He who dwells in the secret place of the Most High shall abide under the shadow of the Almighty. I will say of the LORD, 'He is my refuge and my fortress; my God, in Him I will trust.'",
		Book:      "Psalm",
		Testament: "old",
	},
	{
		Reference: "2 Timothy 3:16-17",
		Text:      "All Scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness, that the man of God may be complete, thoroughly equipped for every good work.",
		Book:      "2 Timothy",
		Testament: "new",
	},
	{
		Reference: "Psalm 119:105",
		Text:      "Your word is a lamp to my feet and a light to my path.",
		Book:      "Psalm",
		Testament: "old",
	},
	{
		Reference: "Hebrews 4:12",
		Text:      "For the word of God is living and powerful, and sharper than any two-edged sword, piercing even to the division of soul and spirit, and of joints and marrow, and is a discerner of the thoughts and intents of the heart.",
		Book:      "Hebrews",
		Testament: "new",
	},
	{
		Reference: "John 17:17",
		Text:      "Sanctify them by Your truth. Your word is truth.",
		Book:      "John",
		Testament: "new",
	},
	{
		Reference: "Matthew 4:4",
		Text:      "But He answered and said, 'It is written, \"Man shall not live by bread alone, but by every word that proceeds from the mouth of God.\"'",
		Book:      "Matthew",
		Testament: "new",
	},
	{
		Reference: "Joshua 1:8",
		Text:      "This Book of the Law shall not depart from your mouth, but you shall meditate in it day and night, that you may observe to do according to all that is written in it. For then you will make your way prosperous, and then you will have good success.",
		Book:      "Joshua",
		Testament: "old",
	},
	{
		Reference: "Philippians 2:9-11",
		Text:      "Therefore God also has highly exalted Him and given Him the name which is above every name, that at the name of Jesus every knee should bow, of those in heaven, and of those on earth, and of those under the earth, and that every tongue should confess that Jesus Christ is Lord, to the glory of God the Father.",
		Book:      "Philippians",
		Testament: "new",
	},
	{
		Reference: "Colossians 1:16-17",
		Text:      "For by Him all things were created that are in heaven and that are on earth, visible and invisible, whether thrones or dominions or principalities or powers. All things were created through Him and for Him. And He is before all things, and in Him all things consist.",
		Book:      "Colossians",
		Testament: "new",
	},
	{
		Reference: "John 1:1",
		Text:      "In the beginning was the Word, and the Word was with God, and the Word was God.",
		Book:      "John",
		Testament: "new",
	},
	{
		Reference: "John 14:6",
		Text:      "Jesus said to him, 'I am the way, the truth, and the life. No one comes to the Father except through Me.'",
		Book:      "John",
		Testament: "new",
	},
	{
		Reference: "Hebrews 13:8",
		Text:      "Jesus Christ is the same yesterday, today, and forever.",
		Book:      "Hebrews",
		Testament: "new",
	},
	{
		Reference: "Revelation 19:16",
		Text:      "And He has on His robe and on His thigh a name written: KING OF KINGS AND LORD OF LORDS.",
		Book:      "Revelation",
		Testament: "new",
	},
	{
		Reference: "Romans 8:38-39",
		Text:      "For I am persuaded that neither death nor life, nor angels nor principalities nor powers, nor things present nor things to come, nor height nor depth, nor any other created thing, shall be able to separate us from the love of God which is in Christ Jesus our Lord.",
		Book:      "Romans",
		Testament: "new",
	},
	{
		Reference: "John 10:28-29",
		Text:      "And I give them eternal life, and they shall never perish; neither shall anyone snatch them out of My hand. My Father, who has given them to Me, is greater than all; and no one is able to snatch them out of My Father's hand.",
		Book:      "John",
		Testament: "new",
	},
	{
		Reference: "1 John 5:13",
		Text:      "These things I have written to you who believe in the name of the Son of God, that you may know that you have eternal life, and that you may continue to believe in the name of the Son of God.",
		Book:      "1 John",
		Testament: "new",
	},
	{
		Reference: "Romans 8:1",
		Text:      "There is therefore now no condemnation to those who are in Christ Jesus, who do not walk according to the flesh, but according to the Spirit.",
		Book:      "Romans",
		Testament: "new",
	},
}
